name: rigor-js-server

services:
  pg:
    image: bitnami/postgresql:17.0.0
    ports:
      - '5433:5433'
    environment:
      - POSTGRES_USER=docker-rigor
      - POSTGRES_PASSWORD=rigor
      - POSTGRES_DB=rigor